const mongoose = require('mongoose');
const Product = require('../models/Product');
require('dotenv').config();

const newIceCreams = [
  {
    name: 'Strawberry Vanilla Swirl',
    description: 'Creamy vanilla with fresh strawberry ribbons',
    category: 'ice-cream',
    price: 5.49,
    image: '/images/products/strawberry-cheesecake.jpg',
    featured: false,
    flavors: ['Vanilla', 'Chocolate', 'Strawberry', 'Mint Chocolate Chip', 'Cookies & Cream', 'Rocky Road', 'Pistachio', 'Salted Caramel', 'Coffee', 'Banana', 'Coconut', 'Lemon', 'Cherry', 'Peanut Butter', 'Bubblegum', 'Mango', 'Blueberry', 'Toffee', 'Honeycomb', 'White Chocolate'],
    toppings: ['Chocolate Chips', 'Sprinkles', 'Caramel Sauce', 'Hot Fudge', 'Whipped Cream', 'Nuts', 'Cherry', 'Oreo Crumbs'],
    inStock: true,
  },
  {
    name: 'Triple Chocolate Delight',
    description: 'Dark, milk, and white chocolate in perfect harmony',
    category: 'ice-cream',
    price: 6.99,
    image: '/images/products/chocolate-brownie.jpg',
    featured: true,
    flavors: ['Vanilla', 'Chocolate', 'Strawberry', 'Mint Chocolate Chip', 'Cookies & Cream', 'Rocky Road', 'Pistachio', 'Salted Caramel', 'Coffee', 'Banana', 'Coconut', 'Lemon', 'Cherry', 'Peanut Butter', 'Bubblegum', 'Mango', 'Blueberry', 'Toffee', 'Honeycomb', 'White Chocolate'],
    toppings: ['Chocolate Chips', 'Sprinkles', 'Caramel Sauce', 'Hot Fudge', 'Whipped Cream', 'Nuts', 'Cherry', 'Oreo Crumbs'],
    inStock: true,
  },
  {
    name: 'Caramel Apple Crunch',
    description: 'Apple ice cream with caramel swirls and crunchy pieces',
    category: 'ice-cream',
    price: 6.29,
    image: '/images/products/vanilla-ice-cream.jpg',
    featured: false,
    flavors: ['Vanilla', 'Chocolate', 'Strawberry', 'Mint Chocolate Chip', 'Cookies & Cream', 'Rocky Road', 'Pistachio', 'Salted Caramel', 'Coffee', 'Banana', 'Coconut', 'Lemon', 'Cherry', 'Peanut Butter', 'Bubblegum', 'Mango', 'Blueberry', 'Toffee', 'Honeycomb', 'White Chocolate'],
    toppings: ['Chocolate Chips', 'Sprinkles', 'Caramel Sauce', 'Hot Fudge', 'Whipped Cream', 'Nuts', 'Cherry', 'Oreo Crumbs'],
    inStock: true,
  },
  {
    name: 'Raspberry Ripple',
    description: 'Vanilla ice cream with tangy raspberry swirls',
    category: 'ice-cream',
    price: 5.79,
    image: '/images/products/strawberry-cheesecake.jpg',
    featured: false,
    flavors: ['Vanilla', 'Chocolate', 'Strawberry', 'Mint Chocolate Chip', 'Cookies & Cream', 'Rocky Road', 'Pistachio', 'Salted Caramel', 'Coffee', 'Banana', 'Coconut', 'Lemon', 'Cherry', 'Peanut Butter', 'Bubblegum', 'Mango', 'Blueberry', 'Toffee', 'Honeycomb', 'White Chocolate'],
    toppings: ['Chocolate Chips', 'Sprinkles', 'Caramel Sauce', 'Hot Fudge', 'Whipped Cream', 'Nuts', 'Cherry', 'Oreo Crumbs'],
    inStock: true,
  },
  {
    name: 'Chocolate Mint Chip',
    description: 'Rich chocolate base with refreshing mint chips',
    category: 'ice-cream',
    price: 5.99,
    image: '/images/products/mint-chocolate.jpg',
    featured: false,
    flavors: ['Vanilla', 'Chocolate', 'Strawberry', 'Mint Chocolate Chip', 'Cookies & Cream', 'Rocky Road', 'Pistachio', 'Salted Caramel', 'Coffee', 'Banana', 'Coconut', 'Lemon', 'Cherry', 'Peanut Butter', 'Bubblegum', 'Mango', 'Blueberry', 'Toffee', 'Honeycomb', 'White Chocolate'],
    toppings: ['Chocolate Chips', 'Sprinkles', 'Caramel Sauce', 'Hot Fudge', 'Whipped Cream', 'Nuts', 'Cherry', 'Oreo Crumbs'],
    inStock: true,
  },
  {
    name: 'Vanilla Bean Supreme',
    description: 'Premium vanilla with real Madagascar vanilla beans',
    category: 'ice-cream',
    price: 5.49,
    image: '/images/products/vanilla-ice-cream.jpg',
    featured: true,
    flavors: ['Vanilla', 'Chocolate', 'Strawberry', 'Mint Chocolate Chip', 'Cookies & Cream', 'Rocky Road', 'Pistachio', 'Salted Caramel', 'Coffee', 'Banana', 'Coconut', 'Lemon', 'Cherry', 'Peanut Butter', 'Bubblegum', 'Mango', 'Blueberry', 'Toffee', 'Honeycomb', 'White Chocolate'],
    toppings: ['Chocolate Chips', 'Sprinkles', 'Caramel Sauce', 'Hot Fudge', 'Whipped Cream', 'Nuts', 'Cherry', 'Oreo Crumbs'],
    inStock: true,
  },
  {
    name: 'Toffee Crunch Surprise',
    description: 'Buttery toffee ice cream with crunchy toffee pieces',
    category: 'ice-cream',
    price: 6.49,
    image: '/images/products/salted-caramel.jpg',
    featured: false,
    flavors: ['Vanilla', 'Chocolate', 'Strawberry', 'Mint Chocolate Chip', 'Cookies & Cream', 'Rocky Road', 'Pistachio', 'Salted Caramel', 'Coffee', 'Banana', 'Coconut', 'Lemon', 'Cherry', 'Peanut Butter', 'Bubblegum', 'Mango', 'Blueberry', 'Toffee', 'Honeycomb', 'White Chocolate'],
    toppings: ['Chocolate Chips', 'Sprinkles', 'Caramel Sauce', 'Hot Fudge', 'Whipped Cream', 'Nuts', 'Cherry', 'Oreo Crumbs'],
    inStock: true,
  },
  {
    name: 'Lemon Sorbet Twist',
    description: 'Refreshing lemon sorbet with creamy vanilla swirls',
    category: 'ice-cream',
    price: 5.29,
    image: '/images/products/lemon-meringue.jpg',
    featured: false,
    flavors: ['Vanilla', 'Chocolate', 'Strawberry', 'Mint Chocolate Chip', 'Cookies & Cream', 'Rocky Road', 'Pistachio', 'Salted Caramel', 'Coffee', 'Banana', 'Coconut', 'Lemon', 'Cherry', 'Peanut Butter', 'Bubblegum', 'Mango', 'Blueberry', 'Toffee', 'Honeycomb', 'White Chocolate'],
    toppings: ['Chocolate Chips', 'Sprinkles', 'Caramel Sauce', 'Hot Fudge', 'Whipped Cream', 'Nuts', 'Cherry', 'Oreo Crumbs'],
    inStock: true,
  },
  {
    name: 'Coconut Mango Paradise',
    description: 'Tropical coconut and mango ice cream blend',
    category: 'ice-cream',
    price: 6.79,
    image: '/images/products/vanilla-ice-cream.jpg',
    featured: true,
    flavors: ['Vanilla', 'Chocolate', 'Strawberry', 'Mint Chocolate Chip', 'Cookies & Cream', 'Rocky Road', 'Pistachio', 'Salted Caramel', 'Coffee', 'Banana', 'Coconut', 'Lemon', 'Cherry', 'Peanut Butter', 'Bubblegum', 'Mango', 'Blueberry', 'Toffee', 'Honeycomb', 'White Chocolate'],
    toppings: ['Chocolate Chips', 'Sprinkles', 'Caramel Sauce', 'Hot Fudge', 'Whipped Cream', 'Nuts', 'Cherry', 'Oreo Crumbs'],
    inStock: true,
  },
  {
    name: 'Espresso Chocolate Chunk',
    description: 'Bold espresso ice cream with dark chocolate chunks',
    category: 'ice-cream',
    price: 6.99,
    image: '/images/products/coffee-crunch.jpg',
    featured: false,
    flavors: ['Vanilla', 'Chocolate', 'Strawberry', 'Mint Chocolate Chip', 'Cookies & Cream', 'Rocky Road', 'Pistachio', 'Salted Caramel', 'Coffee', 'Banana', 'Coconut', 'Lemon', 'Cherry', 'Peanut Butter', 'Bubblegum', 'Mango', 'Blueberry', 'Toffee', 'Honeycomb', 'White Chocolate'],
    toppings: ['Chocolate Chips', 'Sprinkles', 'Caramel Sauce', 'Hot Fudge', 'Whipped Cream', 'Nuts', 'Cherry', 'Oreo Crumbs'],
    inStock: true,
  },
  {
    name: 'Strawberry Cheesecake Swirl',
    description: 'Creamy cheesecake ice cream with strawberry ribbons',
    category: 'ice-cream',
    price: 6.49,
    image: '/images/products/strawberry-cheesecake.jpg',
    featured: true,
    flavors: ['Vanilla', 'Chocolate', 'Strawberry', 'Mint Chocolate Chip', 'Cookies & Cream', 'Rocky Road', 'Pistachio', 'Salted Caramel', 'Coffee', 'Banana', 'Coconut', 'Lemon', 'Cherry', 'Peanut Butter', 'Bubblegum', 'Mango', 'Blueberry', 'Toffee', 'Honeycomb', 'White Chocolate'],
    toppings: ['Chocolate Chips', 'Sprinkles', 'Caramel Sauce', 'Hot Fudge', 'Whipped Cream', 'Nuts', 'Cherry', 'Oreo Crumbs'],
    inStock: true,
  },
  {
    name: 'Pistachio Rose',
    description: 'Delicate pistachio ice cream with rose water essence',
    category: 'ice-cream',
    price: 7.29,
    image: '/images/products/pistachio.jpg',
    featured: false,
    flavors: ['Vanilla', 'Chocolate', 'Strawberry', 'Mint Chocolate Chip', 'Cookies & Cream', 'Rocky Road', 'Pistachio', 'Salted Caramel', 'Coffee', 'Banana', 'Coconut', 'Lemon', 'Cherry', 'Peanut Butter', 'Bubblegum', 'Mango', 'Blueberry', 'Toffee', 'Honeycomb', 'White Chocolate'],
    toppings: ['Chocolate Chips', 'Sprinkles', 'Caramel Sauce', 'Hot Fudge', 'Whipped Cream', 'Nuts', 'Cherry', 'Oreo Crumbs'],
    inStock: true,
  },
  {
    name: 'Blueberry Muffin',
    description: 'Vanilla ice cream with blueberries and muffin pieces',
    category: 'ice-cream',
    price: 6.29,
    image: '/images/products/vanilla-ice-cream.jpg',
    featured: false,
    flavors: ['Vanilla', 'Chocolate', 'Strawberry', 'Mint Chocolate Chip', 'Cookies & Cream', 'Rocky Road', 'Pistachio', 'Salted Caramel', 'Coffee', 'Banana', 'Coconut', 'Lemon', 'Cherry', 'Peanut Butter', 'Bubblegum', 'Mango', 'Blueberry', 'Toffee', 'Honeycomb', 'White Chocolate'],
    toppings: ['Chocolate Chips', 'Sprinkles', 'Caramel Sauce', 'Hot Fudge', 'Whipped Cream', 'Nuts', 'Cherry', 'Oreo Crumbs'],
    inStock: true,
  },
  {
    name: 'Chocolate Peanut Butter Swirl',
    description: 'Rich chocolate with creamy peanut butter ribbons',
    category: 'ice-cream',
    price: 6.79,
    image: '/images/products/peanut-butter.jpg',
    featured: true,
    flavors: ['Vanilla', 'Chocolate', 'Strawberry', 'Mint Chocolate Chip', 'Cookies & Cream', 'Rocky Road', 'Pistachio', 'Salted Caramel', 'Coffee', 'Banana', 'Coconut', 'Lemon', 'Cherry', 'Peanut Butter', 'Bubblegum', 'Mango', 'Blueberry', 'Toffee', 'Honeycomb', 'White Chocolate'],
    toppings: ['Chocolate Chips', 'Sprinkles', 'Caramel Sauce', 'Hot Fudge', 'Whipped Cream', 'Nuts', 'Cherry', 'Oreo Crumbs'],
    inStock: true,
  },
  {
    name: 'Honeycomb Crunch Delight',
    description: 'Sweet honey ice cream with crunchy honeycomb pieces',
    category: 'ice-cream',
    price: 6.49,
    image: '/images/products/vanilla-ice-cream.jpg',
    featured: false,
    flavors: ['Vanilla', 'Chocolate', 'Strawberry', 'Mint Chocolate Chip', 'Cookies & Cream', 'Rocky Road', 'Pistachio', 'Salted Caramel', 'Coffee', 'Banana', 'Coconut', 'Lemon', 'Cherry', 'Peanut Butter', 'Bubblegum', 'Mango', 'Blueberry', 'Toffee', 'Honeycomb', 'White Chocolate'],
    toppings: ['Chocolate Chips', 'Sprinkles', 'Caramel Sauce', 'Hot Fudge', 'Whipped Cream', 'Nuts', 'Cherry', 'Oreo Crumbs'],
    inStock: true,
  },
  {
    name: 'Cherry Vanilla Supreme',
    description: 'Premium vanilla with sweet cherry pieces',
    category: 'ice-cream',
    price: 5.99,
    image: '/images/products/strawberry-cheesecake.jpg',
    featured: false,
    flavors: ['Vanilla', 'Chocolate', 'Strawberry', 'Mint Chocolate Chip', 'Cookies & Cream', 'Rocky Road', 'Pistachio', 'Salted Caramel', 'Coffee', 'Banana', 'Coconut', 'Lemon', 'Cherry', 'Peanut Butter', 'Bubblegum', 'Mango', 'Blueberry', 'Toffee', 'Honeycomb', 'White Chocolate'],
    toppings: ['Chocolate Chips', 'Sprinkles', 'Caramel Sauce', 'Hot Fudge', 'Whipped Cream', 'Nuts', 'Cherry', 'Oreo Crumbs'],
    inStock: true,
  },
  {
    name: 'Banana Foster',
    description: 'Banana ice cream with caramel and rum flavoring',
    category: 'ice-cream',
    price: 6.99,
    image: '/images/products/vanilla-ice-cream.jpg',
    featured: false,
    flavors: ['Vanilla', 'Chocolate', 'Strawberry', 'Mint Chocolate Chip', 'Cookies & Cream', 'Rocky Road', 'Pistachio', 'Salted Caramel', 'Coffee', 'Banana', 'Coconut', 'Lemon', 'Cherry', 'Peanut Butter', 'Bubblegum', 'Mango', 'Blueberry', 'Toffee', 'Honeycomb', 'White Chocolate'],
    toppings: ['Chocolate Chips', 'Sprinkles', 'Caramel Sauce', 'Hot Fudge', 'Whipped Cream', 'Nuts', 'Cherry', 'Oreo Crumbs'],
    inStock: true,
  },
  {
    name: 'White Chocolate Raspberry',
    description: 'Creamy white chocolate with tart raspberry swirls',
    category: 'ice-cream',
    price: 6.79,
    image: '/images/products/strawberry-cheesecake.jpg',
    featured: true,
    flavors: ['Vanilla', 'Chocolate', 'Strawberry', 'Mint Chocolate Chip', 'Cookies & Cream', 'Rocky Road', 'Pistachio', 'Salted Caramel', 'Coffee', 'Banana', 'Coconut', 'Lemon', 'Cherry', 'Peanut Butter', 'Bubblegum', 'Mango', 'Blueberry', 'Toffee', 'Honeycomb', 'White Chocolate'],
    toppings: ['Chocolate Chips', 'Sprinkles', 'Caramel Sauce', 'Hot Fudge', 'Whipped Cream', 'Nuts', 'Cherry', 'Oreo Crumbs'],
    inStock: true,
  },
  {
    name: 'Maple Pecan Praline',
    description: 'Rich maple ice cream with candied pecan pieces',
    category: 'ice-cream',
    price: 7.49,
    image: '/images/products/vanilla-ice-cream.jpg',
    featured: false,
    flavors: ['Vanilla', 'Chocolate', 'Strawberry', 'Mint Chocolate Chip', 'Cookies & Cream', 'Rocky Road', 'Pistachio', 'Salted Caramel', 'Coffee', 'Banana', 'Coconut', 'Lemon', 'Cherry', 'Peanut Butter', 'Bubblegum', 'Mango', 'Blueberry', 'Toffee', 'Honeycomb', 'White Chocolate'],
    toppings: ['Chocolate Chips', 'Sprinkles', 'Caramel Sauce', 'Hot Fudge', 'Whipped Cream', 'Nuts', 'Cherry', 'Oreo Crumbs'],
    inStock: true,
  },
  {
    name: 'Cotton Candy Dream',
    description: 'Sweet cotton candy flavored ice cream with colorful swirls',
    category: 'ice-cream',
    price: 5.79,
    image: '/images/products/rainbow-cone.jpg',
    featured: false,
    flavors: ['Vanilla', 'Chocolate', 'Strawberry', 'Mint Chocolate Chip', 'Cookies & Cream', 'Rocky Road', 'Pistachio', 'Salted Caramel', 'Coffee', 'Banana', 'Coconut', 'Lemon', 'Cherry', 'Peanut Butter', 'Bubblegum', 'Mango', 'Blueberry', 'Toffee', 'Honeycomb', 'White Chocolate'],
    toppings: ['Chocolate Chips', 'Sprinkles', 'Caramel Sauce', 'Hot Fudge', 'Whipped Cream', 'Nuts', 'Cherry', 'Oreo Crumbs'],
    inStock: true,
  },
  {
    name: 'Chocolate Brownie Fudge',
    description: 'Decadent chocolate ice cream with brownie chunks and fudge',
    category: 'ice-cream',
    price: 7.29,
    image: '/images/products/chocolate-brownie.jpg',
    featured: true,
    flavors: ['Vanilla', 'Chocolate', 'Strawberry', 'Mint Chocolate Chip', 'Cookies & Cream', 'Rocky Road', 'Pistachio', 'Salted Caramel', 'Coffee', 'Banana', 'Coconut', 'Lemon', 'Cherry', 'Peanut Butter', 'Bubblegum', 'Mango', 'Blueberry', 'Toffee', 'Honeycomb', 'White Chocolate'],
    toppings: ['Chocolate Chips', 'Sprinkles', 'Caramel Sauce', 'Hot Fudge', 'Whipped Cream', 'Nuts', 'Cherry', 'Oreo Crumbs'],
    inStock: true,
  },
  {
    name: 'Lavender Honey',
    description: 'Delicate lavender ice cream with natural honey swirls',
    category: 'ice-cream',
    price: 6.99,
    image: '/images/products/vanilla-ice-cream.jpg',
    featured: false,
    flavors: ['Vanilla', 'Chocolate', 'Strawberry', 'Mint Chocolate Chip', 'Cookies & Cream', 'Rocky Road', 'Pistachio', 'Salted Caramel', 'Coffee', 'Banana', 'Coconut', 'Lemon', 'Cherry', 'Peanut Butter', 'Bubblegum', 'Mango', 'Blueberry', 'Toffee', 'Honeycomb', 'White Chocolate'],
    toppings: ['Chocolate Chips', 'Sprinkles', 'Caramel Sauce', 'Hot Fudge', 'Whipped Cream', 'Nuts', 'Cherry', 'Oreo Crumbs'],
    inStock: true,
  },
  {
    name: 'Cinnamon Roll Swirl',
    description: 'Cinnamon ice cream with sweet roll pieces and glaze',
    category: 'ice-cream',
    price: 6.79,
    image: '/images/products/vanilla-ice-cream.jpg',
    featured: false,
    flavors: ['Vanilla', 'Chocolate', 'Strawberry', 'Mint Chocolate Chip', 'Cookies & Cream', 'Rocky Road', 'Pistachio', 'Salted Caramel', 'Coffee', 'Banana', 'Coconut', 'Lemon', 'Cherry', 'Peanut Butter', 'Bubblegum', 'Mango', 'Blueberry', 'Toffee', 'Honeycomb', 'White Chocolate'],
    toppings: ['Chocolate Chips', 'Sprinkles', 'Caramel Sauce', 'Hot Fudge', 'Whipped Cream', 'Nuts', 'Cherry', 'Oreo Crumbs'],
    inStock: true,
  },
  {
    name: 'Tropical Passion Fruit',
    description: 'Exotic passion fruit ice cream with tropical fruit pieces',
    category: 'ice-cream',
    price: 6.49,
    image: '/images/products/vanilla-ice-cream.jpg',
    featured: true,
    flavors: ['Vanilla', 'Chocolate', 'Strawberry', 'Mint Chocolate Chip', 'Cookies & Cream', 'Rocky Road', 'Pistachio', 'Salted Caramel', 'Coffee', 'Banana', 'Coconut', 'Lemon', 'Cherry', 'Peanut Butter', 'Bubblegum', 'Mango', 'Blueberry', 'Toffee', 'Honeycomb', 'White Chocolate'],
    toppings: ['Chocolate Chips', 'Sprinkles', 'Caramel Sauce', 'Hot Fudge', 'Whipped Cream', 'Nuts', 'Cherry', 'Oreo Crumbs'],
    inStock: true,
  }
];

const addIceCreams = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost:27017/creamychills');
    
    await Product.insertMany(newIceCreams);
    console.log('24 new ice creams added successfully!');
    process.exit(0);
  } catch (error) {
    console.error('Error adding ice creams:', error);
    process.exit(1);
  }
};

addIceCreams();