const mongoose = require('mongoose');
const Product = require('../models/Product');
require('dotenv').config();

const equisIceCreams = [
  { name: 'Equis Vanilla Classic', description: 'Premium Equis vanilla ice cream', category: 'ice-cream', price: 5.99, image: '/images/products/vanilla-ice-cream.jpg', featured: false, flavors: ['Vanilla', 'Chocolate', 'Strawberry', 'Mint Chocolate Chip', 'Cookies & Cream', 'Rocky Road', 'Pistachio', 'Salted Caramel', 'Coffee', 'Banana', 'Coconut', 'Lemon', 'Cherry', 'Peanut Butter', 'Bubblegum', 'Mango', 'Blueberry', 'Toffee', 'Honeycomb', 'White Chocolate'], toppings: ['Chocolate Chips', 'Sprinkles', 'Caramel Sauce', 'Hot Fudge', 'Whipped Cream', 'Nuts', 'Cherry', 'Oreo Crumbs'], inStock: true },
  { name: 'Equis Chocolate Supreme', description: 'Rich Equis chocolate ice cream', category: 'ice-cream', price: 6.49, image: '/images/products/chocolate-brownie.jpg', featured: true, flavors: ['Vanilla', 'Chocolate', 'Strawberry', 'Mint Chocolate Chip', 'Cookies & Cream', 'Rocky Road', 'Pistachio', 'Salted Caramel', 'Coffee', 'Banana', 'Coconut', 'Lemon', 'Cherry', 'Peanut Butter', 'Bubblegum', 'Mango', 'Blueberry', 'Toffee', 'Honeycomb', 'White Chocolate'], toppings: ['Chocolate Chips', 'Sprinkles', 'Caramel Sauce', 'Hot Fudge', 'Whipped Cream', 'Nuts', 'Cherry', 'Oreo Crumbs'], inStock: true },
  { name: 'Equis Strawberry Delight', description: 'Fresh Equis strawberry ice cream', category: 'ice-cream', price: 5.79, image: '/images/products/strawberry-cheesecake.jpg', featured: false, flavors: ['Vanilla', 'Chocolate', 'Strawberry', 'Mint Chocolate Chip', 'Cookies & Cream', 'Rocky Road', 'Pistachio', 'Salted Caramel', 'Coffee', 'Banana', 'Coconut', 'Lemon', 'Cherry', 'Peanut Butter', 'Bubblegum', 'Mango', 'Blueberry', 'Toffee', 'Honeycomb', 'White Chocolate'], toppings: ['Chocolate Chips', 'Sprinkles', 'Caramel Sauce', 'Hot Fudge', 'Whipped Cream', 'Nuts', 'Cherry', 'Oreo Crumbs'], inStock: true },
  { name: 'Equis Mint Chocolate Chip', description: 'Refreshing Equis mint ice cream', category: 'ice-cream', price: 6.29, image: '/images/products/mint-chocolate.jpg', featured: false, flavors: ['Vanilla', 'Chocolate', 'Strawberry', 'Mint Chocolate Chip', 'Cookies & Cream', 'Rocky Road', 'Pistachio', 'Salted Caramel', 'Coffee', 'Banana', 'Coconut', 'Lemon', 'Cherry', 'Peanut Butter', 'Bubblegum', 'Mango', 'Blueberry', 'Toffee', 'Honeycomb', 'White Chocolate'], toppings: ['Chocolate Chips', 'Sprinkles', 'Caramel Sauce', 'Hot Fudge', 'Whipped Cream', 'Nuts', 'Cherry', 'Oreo Crumbs'], inStock: true },
  { name: 'Equis Cookies & Cream', description: 'Creamy Equis vanilla with cookies', category: 'ice-cream', price: 6.49, image: '/images/products/cookies-cream.jpg', featured: true, flavors: ['Vanilla', 'Chocolate', 'Strawberry', 'Mint Chocolate Chip', 'Cookies & Cream', 'Rocky Road', 'Pistachio', 'Salted Caramel', 'Coffee', 'Banana', 'Coconut', 'Lemon', 'Cherry', 'Peanut Butter', 'Bubblegum', 'Mango', 'Blueberry', 'Toffee', 'Honeycomb', 'White Chocolate'], toppings: ['Chocolate Chips', 'Sprinkles', 'Caramel Sauce', 'Hot Fudge', 'Whipped Cream', 'Nuts', 'Cherry', 'Oreo Crumbs'], inStock: true },
  { name: 'Equis Rocky Road', description: 'Chocolate Equis with marshmallows', category: 'ice-cream', price: 6.99, image: '/images/products/rocky-road.jpg', featured: false, flavors: ['Vanilla', 'Chocolate', 'Strawberry', 'Mint Chocolate Chip', 'Cookies & Cream', 'Rocky Road', 'Pistachio', 'Salted Caramel', 'Coffee', 'Banana', 'Coconut', 'Lemon', 'Cherry', 'Peanut Butter', 'Bubblegum', 'Mango', 'Blueberry', 'Toffee', 'Honeycomb', 'White Chocolate'], toppings: ['Chocolate Chips', 'Sprinkles', 'Caramel Sauce', 'Hot Fudge', 'Whipped Cream', 'Nuts', 'Cherry', 'Oreo Crumbs'], inStock: true },
  { name: 'Equis Pistachio Dream', description: 'Authentic Equis pistachio ice cream', category: 'ice-cream', price: 7.49, image: '/images/products/pistachio.jpg', featured: false, flavors: ['Vanilla', 'Chocolate', 'Strawberry', 'Mint Chocolate Chip', 'Cookies & Cream', 'Rocky Road', 'Pistachio', 'Salted Caramel', 'Coffee', 'Banana', 'Coconut', 'Lemon', 'Cherry', 'Peanut Butter', 'Bubblegum', 'Mango', 'Blueberry', 'Toffee', 'Honeycomb', 'White Chocolate'], toppings: ['Chocolate Chips', 'Sprinkles', 'Caramel Sauce', 'Hot Fudge', 'Whipped Cream', 'Nuts', 'Cherry', 'Oreo Crumbs'], inStock: true },
  { name: 'Equis Salted Caramel', description: 'Sweet and salty Equis caramel', category: 'ice-cream', price: 6.79, image: '/images/products/salted-caramel.jpg', featured: true, flavors: ['Vanilla', 'Chocolate', 'Strawberry', 'Mint Chocolate Chip', 'Cookies & Cream', 'Rocky Road', 'Pistachio', 'Salted Caramel', 'Coffee', 'Banana', 'Coconut', 'Lemon', 'Cherry', 'Peanut Butter', 'Bubblegum', 'Mango', 'Blueberry', 'Toffee', 'Honeycomb', 'White Chocolate'], toppings: ['Chocolate Chips', 'Sprinkles', 'Caramel Sauce', 'Hot Fudge', 'Whipped Cream', 'Nuts', 'Cherry', 'Oreo Crumbs'], inStock: true },
  { name: 'Equis Coffee Crunch', description: 'Bold Equis coffee ice cream', category: 'ice-cream', price: 6.99, image: '/images/products/coffee-crunch.jpg', featured: false, flavors: ['Vanilla', 'Chocolate', 'Strawberry', 'Mint Chocolate Chip', 'Cookies & Cream', 'Rocky Road', 'Pistachio', 'Salted Caramel', 'Coffee', 'Banana', 'Coconut', 'Lemon', 'Cherry', 'Peanut Butter', 'Bubblegum', 'Mango', 'Blueberry', 'Toffee', 'Honeycomb', 'White Chocolate'], toppings: ['Chocolate Chips', 'Sprinkles', 'Caramel Sauce', 'Hot Fudge', 'Whipped Cream', 'Nuts', 'Cherry', 'Oreo Crumbs'], inStock: true },
  { name: 'Equis Rainbow Cone', description: 'Colorful Equis rainbow ice cream', category: 'ice-cream', price: 6.29, image: '/images/products/rainbow-cone.jpg', featured: false, flavors: ['Vanilla', 'Chocolate', 'Strawberry', 'Mint Chocolate Chip', 'Cookies & Cream', 'Rocky Road', 'Pistachio', 'Salted Caramel', 'Coffee', 'Banana', 'Coconut', 'Lemon', 'Cherry', 'Peanut Butter', 'Bubblegum', 'Mango', 'Blueberry', 'Toffee', 'Honeycomb', 'White Chocolate'], toppings: ['Chocolate Chips', 'Sprinkles', 'Caramel Sauce', 'Hot Fudge', 'Whipped Cream', 'Nuts', 'Cherry', 'Oreo Crumbs'], inStock: true },
  { name: 'Equis Mango Sorbet', description: 'Tropical Equis mango sorbet', category: 'ice-cream', price: 6.49, image: '/images/products/mango-sorbet.jpg', featured: false, flavors: ['Vanilla', 'Chocolate', 'Strawberry', 'Mint Chocolate Chip', 'Cookies & Cream', 'Rocky Road', 'Pistachio', 'Salted Caramel', 'Coffee', 'Banana', 'Coconut', 'Lemon', 'Cherry', 'Peanut Butter', 'Bubblegum', 'Mango', 'Blueberry', 'Toffee', 'Honeycomb', 'White Chocolate'], toppings: ['Chocolate Chips', 'Sprinkles', 'Caramel Sauce', 'Hot Fudge', 'Whipped Cream', 'Nuts', 'Cherry', 'Oreo Crumbs'], inStock: true },
  { name: 'Equis Lemon Sorbet', description: 'Refreshing Equis lemon sorbet', category: 'ice-cream', price: 5.49, image: '/images/products/lemon-meringue.jpg', featured: false, flavors: ['Vanilla', 'Chocolate', 'Strawberry', 'Mint Chocolate Chip', 'Cookies & Cream', 'Rocky Road', 'Pistachio', 'Salted Caramel', 'Coffee', 'Banana', 'Coconut', 'Lemon', 'Cherry', 'Peanut Butter', 'Bubblegum', 'Mango', 'Blueberry', 'Toffee', 'Honeycomb', 'White Chocolate'], toppings: ['Chocolate Chips', 'Sprinkles', 'Caramel Sauce', 'Hot Fudge', 'Whipped Cream', 'Nuts', 'Cherry', 'Oreo Crumbs'], inStock: true },
  { name: 'Equis Chocolate Cake', description: 'Rich Equis chocolate cake flavor', category: 'ice-cream', price: 6.79, image: '/images/products/chocolate-cake.jpg', featured: true, flavors: ['Vanilla', 'Chocolate', 'Strawberry', 'Mint Chocolate Chip', 'Cookies & Cream', 'Rocky Road', 'Pistachio', 'Salted Caramel', 'Coffee', 'Banana', 'Coconut', 'Lemon', 'Cherry', 'Peanut Butter', 'Bubblegum', 'Mango', 'Blueberry', 'Toffee', 'Honeycomb', 'White Chocolate'], toppings: ['Chocolate Chips', 'Sprinkles', 'Caramel Sauce', 'Hot Fudge', 'Whipped Cream', 'Nuts', 'Cherry', 'Oreo Crumbs'], inStock: true },
  { name: 'Equis Peanut Butter Cup', description: 'Rich Equis peanut butter ice cream', category: 'ice-cream', price: 7.29, image: '/images/products/peanut-butter.jpg', featured: false, flavors: ['Vanilla', 'Chocolate', 'Strawberry', 'Mint Chocolate Chip', 'Cookies & Cream', 'Rocky Road', 'Pistachio', 'Salted Caramel', 'Coffee', 'Banana', 'Coconut', 'Lemon', 'Cherry', 'Peanut Butter', 'Bubblegum', 'Mango', 'Blueberry', 'Toffee', 'Honeycomb', 'White Chocolate'], toppings: ['Chocolate Chips', 'Sprinkles', 'Caramel Sauce', 'Hot Fudge', 'Whipped Cream', 'Nuts', 'Cherry', 'Oreo Crumbs'], inStock: true },
  { name: 'Equis Black Forest', description: 'Cherry and chocolate Equis delight', category: 'ice-cream', price: 5.99, image: '/images/products/black-forest.jpg', featured: false, flavors: ['Vanilla', 'Chocolate', 'Strawberry', 'Mint Chocolate Chip', 'Cookies & Cream', 'Rocky Road', 'Pistachio', 'Salted Caramel', 'Coffee', 'Banana', 'Coconut', 'Lemon', 'Cherry', 'Peanut Butter', 'Bubblegum', 'Mango', 'Blueberry', 'Toffee', 'Honeycomb', 'White Chocolate'], toppings: ['Chocolate Chips', 'Sprinkles', 'Caramel Sauce', 'Hot Fudge', 'Whipped Cream', 'Nuts', 'Cherry', 'Oreo Crumbs'], inStock: true },
  { name: 'Equis Carrot Cake', description: 'Spiced Equis carrot cake flavor', category: 'ice-cream', price: 6.49, image: '/images/products/carrot-cake.jpg', featured: false, flavors: ['Vanilla', 'Chocolate', 'Strawberry', 'Mint Chocolate Chip', 'Cookies & Cream', 'Rocky Road', 'Pistachio', 'Salted Caramel', 'Coffee', 'Banana', 'Coconut', 'Lemon', 'Cherry', 'Peanut Butter', 'Bubblegum', 'Mango', 'Blueberry', 'Toffee', 'Honeycomb', 'White Chocolate'], toppings: ['Chocolate Chips', 'Sprinkles', 'Caramel Sauce', 'Hot Fudge', 'Whipped Cream', 'Nuts', 'Cherry', 'Oreo Crumbs'], inStock: true },
  { name: 'Equis Lemon Cake', description: 'Zesty Equis lemon cake ice cream', category: 'ice-cream', price: 6.99, image: '/images/products/lemon-cake.jpg', featured: true, flavors: ['Vanilla', 'Chocolate', 'Strawberry', 'Mint Chocolate Chip', 'Cookies & Cream', 'Rocky Road', 'Pistachio', 'Salted Caramel', 'Coffee', 'Banana', 'Coconut', 'Lemon', 'Cherry', 'Peanut Butter', 'Bubblegum', 'Mango', 'Blueberry', 'Toffee', 'Honeycomb', 'White Chocolate'], toppings: ['Chocolate Chips', 'Sprinkles', 'Caramel Sauce', 'Hot Fudge', 'Whipped Cream', 'Nuts', 'Cherry', 'Oreo Crumbs'], inStock: true },
  { name: 'Equis Red Velvet', description: 'Classic Equis red velvet flavor', category: 'ice-cream', price: 6.79, image: '/images/products/red-velvet-cake.jpg', featured: false, flavors: ['Vanilla', 'Chocolate', 'Strawberry', 'Mint Chocolate Chip', 'Cookies & Cream', 'Rocky Road', 'Pistachio', 'Salted Caramel', 'Coffee', 'Banana', 'Coconut', 'Lemon', 'Cherry', 'Peanut Butter', 'Bubblegum', 'Mango', 'Blueberry', 'Toffee', 'Honeycomb', 'White Chocolate'], toppings: ['Chocolate Chips', 'Sprinkles', 'Caramel Sauce', 'Hot Fudge', 'Whipped Cream', 'Nuts', 'Cherry', 'Oreo Crumbs'], inStock: true },
  { name: 'Equis Neapolitan', description: 'Classic Equis three-flavor combo', category: 'ice-cream', price: 6.29, image: '/images/products/neapolitan.jpg', featured: false, flavors: ['Vanilla', 'Chocolate', 'Strawberry', 'Mint Chocolate Chip', 'Cookies & Cream', 'Rocky Road', 'Pistachio', 'Salted Caramel', 'Coffee', 'Banana', 'Coconut', 'Lemon', 'Cherry', 'Peanut Butter', 'Bubblegum', 'Mango', 'Blueberry', 'Toffee', 'Honeycomb', 'White Chocolate'], toppings: ['Chocolate Chips', 'Sprinkles', 'Caramel Sauce', 'Hot Fudge', 'Whipped Cream', 'Nuts', 'Cherry', 'Oreo Crumbs'], inStock: true },
  { name: 'Equis Vanilla Sponge', description: 'Light Equis vanilla sponge flavor', category: 'ice-cream', price: 7.29, image: '/images/products/vanilla-sponge.jpg', featured: false, flavors: ['Vanilla', 'Chocolate', 'Strawberry', 'Mint Chocolate Chip', 'Cookies & Cream', 'Rocky Road', 'Pistachio', 'Salted Caramel', 'Coffee', 'Banana', 'Coconut', 'Lemon', 'Cherry', 'Peanut Butter', 'Bubblegum', 'Mango', 'Blueberry', 'Toffee', 'Honeycomb', 'White Chocolate'], toppings: ['Chocolate Chips', 'Sprinkles', 'Caramel Sauce', 'Hot Fudge', 'Whipped Cream', 'Nuts', 'Cherry', 'Oreo Crumbs'], inStock: true },
  { name: 'Equis Strawberry Shortcake', description: 'Sweet Equis strawberry shortcake', category: 'ice-cream', price: 7.99, image: '/images/products/strawberry-shortcake.jpg', featured: true, flavors: ['Vanilla', 'Chocolate', 'Strawberry', 'Mint Chocolate Chip', 'Cookies & Cream', 'Rocky Road', 'Pistachio', 'Salted Caramel', 'Coffee', 'Banana', 'Coconut', 'Lemon', 'Cherry', 'Peanut Butter', 'Bubblegum', 'Mango', 'Blueberry', 'Toffee', 'Honeycomb', 'White Chocolate'], toppings: ['Chocolate Chips', 'Sprinkles', 'Caramel Sauce', 'Hot Fudge', 'Whipped Cream', 'Nuts', 'Cherry', 'Oreo Crumbs'], inStock: true },
  { name: 'Equis Belgian Waffle', description: 'Crispy Equis waffle ice cream', category: 'ice-cream', price: 6.49, image: '/images/products/belgian-waffle.jpg', featured: false, flavors: ['Vanilla', 'Chocolate', 'Strawberry', 'Mint Chocolate Chip', 'Cookies & Cream', 'Rocky Road', 'Pistachio', 'Salted Caramel', 'Coffee', 'Banana', 'Coconut', 'Lemon', 'Cherry', 'Peanut Butter', 'Bubblegum', 'Mango', 'Blueberry', 'Toffee', 'Honeycomb', 'White Chocolate'], toppings: ['Chocolate Chips', 'Sprinkles', 'Caramel Sauce', 'Hot Fudge', 'Whipped Cream', 'Nuts', 'Cherry', 'Oreo Crumbs'], inStock: true },
  { name: 'Equis Blueberry Waffle', description: 'Fruity Equis blueberry waffle', category: 'ice-cream', price: 6.29, image: '/images/products/blueberry-waffle.jpg', featured: false, flavors: ['Vanilla', 'Chocolate', 'Strawberry', 'Mint Chocolate Chip', 'Cookies & Cream', 'Rocky Road', 'Pistachio', 'Salted Caramel', 'Coffee', 'Banana', 'Coconut', 'Lemon', 'Cherry', 'Peanut Butter', 'Bubblegum', 'Mango', 'Blueberry', 'Toffee', 'Honeycomb', 'White Chocolate'], toppings: ['Chocolate Chips', 'Sprinkles', 'Caramel Sauce', 'Hot Fudge', 'Whipped Cream', 'Nuts', 'Cherry', 'Oreo Crumbs'], inStock: true },
  { name: 'Equis Strawberry Waffle', description: 'Sweet Equis strawberry waffle', category: 'ice-cream', price: 5.99, image: '/images/products/strawberry-waffle.jpg', featured: false, flavors: ['Vanilla', 'Chocolate', 'Strawberry', 'Mint Chocolate Chip', 'Cookies & Cream', 'Rocky Road', 'Pistachio', 'Salted Caramel', 'Coffee', 'Banana', 'Coconut', 'Lemon', 'Cherry', 'Peanut Butter', 'Bubblegum', 'Mango', 'Blueberry', 'Toffee', 'Honeycomb', 'White Chocolate'], toppings: ['Chocolate Chips', 'Sprinkles', 'Caramel Sauce', 'Hot Fudge', 'Whipped Cream', 'Nuts', 'Cherry', 'Oreo Crumbs'], inStock: true }
];

async function addEquisIceCreams() {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('Connected to MongoDB');

    // Remove existing Equis ice creams to avoid duplicates
    await Product.deleteMany({ name: { $regex: /^Equis/, $options: 'i' } });
    console.log('Removed existing Equis ice creams');

    // Also remove old ice cream products to make room
    await Product.deleteMany({ category: 'ice-cream', name: { $not: { $regex: /^Equis/, $options: 'i' } } });
    console.log('Removed old ice cream products');

    // Add new Equis ice creams
    const result = await Product.insertMany(equisIceCreams);
    console.log(`Added ${result.length} Equis ice cream products`);

    await mongoose.connection.close();
    console.log('Database connection closed');
  } catch (error) {
    console.error('Error adding Equis ice creams:', error);
    process.exit(1);
  }
}

addEquisIceCreams();