const mongoose = require('mongoose');
const Product = require('../models/Product');
require('dotenv').config();

const newIceCreams = [
  {
    name: 'Double Chocolate Fudge',
    description: 'Rich double chocolate ice cream with fudge swirls',
    category: 'ice-cream',
    price: 6.49,
    image: '/images/products/chocolate-brownie.jpg',
    featured: false,
    flavors: ['Double Chocolate'],
    toppings: ['Chocolate Chips', 'Fudge Sauce', 'Brownie Bits', 'Whipped Cream'],
    inStock: true,
  },
  {
    name: 'Strawberry Swirl',
    description: 'Creamy vanilla with fresh strawberry swirls',
    category: 'ice-cream',
    price: 5.79,
    image: '/images/products/strawberry-cheesecake.jpg',
    featured: false,
    flavors: ['Strawberry Vanilla'],
    toppings: ['Fresh Strawberries', 'Strawberry Sauce', 'Vanilla Wafers'],
    inStock: true,
  },
  {
    name: 'Caramel Crunch',
    description: 'Caramel ice cream with crunchy toffee pieces',
    category: 'ice-cream',
    price: 6.29,
    image: '/images/products/salted-caramel.jpg',
    featured: false,
    flavors: ['Caramel'],
    toppings: ['Toffee Bits', 'Caramel Sauce', 'Crushed Nuts'],
    inStock: true,
  },
  {
    name: 'Vanilla Oreo',
    description: 'Classic vanilla with crushed Oreo cookies',
    category: 'ice-cream',
    price: 5.99,
    image: '/images/products/cookies-cream.jpg',
    featured: true,
    flavors: ['Vanilla'],
    toppings: ['Oreo Pieces', 'Cookie Crumbs', 'Chocolate Sauce'],
    inStock: true,
  },
  {
    name: 'Mint Chip Delight',
    description: 'Cool mint ice cream loaded with chocolate chips',
    category: 'ice-cream',
    price: 5.89,
    image: '/images/products/mint-chocolate.jpg',
    featured: false,
    flavors: ['Mint'],
    toppings: ['Mini Chocolate Chips', 'Mint Leaves', 'Hot Fudge'],
    inStock: true,
  },
  {
    name: 'Berry Blast',
    description: 'Mixed berry ice cream with real fruit pieces',
    category: 'ice-cream',
    price: 6.19,
    image: '/images/products/strawberry-cheesecake.jpg',
    featured: false,
    flavors: ['Mixed Berry'],
    toppings: ['Fresh Berries', 'Berry Sauce', 'Granola'],
    inStock: true,
  },
  {
    name: 'Chocolate Chip Cookie Dough',
    description: 'Vanilla ice cream with edible cookie dough chunks',
    category: 'ice-cream',
    price: 6.79,
    image: '/images/products/cookies-cream.jpg',
    featured: true,
    flavors: ['Cookie Dough'],
    toppings: ['Cookie Dough Pieces', 'Chocolate Chips', 'Caramel Drizzle'],
    inStock: true,
  },
  {
    name: 'Honeycomb Crunch',
    description: 'Sweet honey ice cream with crunchy honeycomb pieces',
    category: 'ice-cream',
    price: 6.49,
    image: '/images/products/vanilla-ice-cream.jpg',
    featured: false,
    flavors: ['Honey'],
    toppings: ['Honeycomb Pieces', 'Honey Drizzle', 'Crushed Biscuits'],
    inStock: true,
  },
  {
    name: 'Espresso Chocolate',
    description: 'Rich espresso ice cream with dark chocolate chunks',
    category: 'ice-cream',
    price: 6.99,
    image: '/images/products/coffee-crunch.jpg',
    featured: false,
    flavors: ['Espresso'],
    toppings: ['Dark Chocolate Chunks', 'Coffee Beans', 'Whipped Cream'],
    inStock: true,
  },
  {
    name: 'Banana Caramel',
    description: 'Banana ice cream with rich caramel swirls',
    category: 'ice-cream',
    price: 5.99,
    image: '/images/products/vanilla-ice-cream.jpg',
    featured: false,
    flavors: ['Banana'],
    toppings: ['Banana Slices', 'Caramel Sauce', 'Crushed Nuts'],
    inStock: true,
  },
  {
    name: 'Toffee Apple',
    description: 'Apple cinnamon ice cream with toffee pieces',
    category: 'ice-cream',
    price: 6.29,
    image: '/images/products/vanilla-ice-cream.jpg',
    featured: false,
    flavors: ['Apple Cinnamon'],
    toppings: ['Apple Pieces', 'Toffee Bits', 'Cinnamon Sugar'],
    inStock: true,
  },
  {
    name: 'White Chocolate Raspberry',
    description: 'White chocolate ice cream with raspberry swirls',
    category: 'ice-cream',
    price: 6.79,
    image: '/images/products/strawberry-cheesecake.jpg',
    featured: true,
    flavors: ['White Chocolate'],
    toppings: ['Fresh Raspberries', 'White Chocolate Chips', 'Berry Sauce'],
    inStock: true,
  },
  {
    name: 'Bubblegum Blast',
    description: 'Fun bubblegum flavored ice cream with colorful pieces',
    category: 'ice-cream',
    price: 5.49,
    image: '/images/products/rainbow-cone.jpg',
    featured: false,
    flavors: ['Bubblegum'],
    toppings: ['Bubblegum Pieces', 'Rainbow Sprinkles', 'Pop Rocks'],
    inStock: true,
  },
  {
    name: 'Lemon Cheesecake',
    description: 'Tangy lemon ice cream with cheesecake chunks',
    category: 'ice-cream',
    price: 6.49,
    image: '/images/products/lemon-meringue.jpg',
    featured: false,
    flavors: ['Lemon'],
    toppings: ['Cheesecake Pieces', 'Lemon Zest', 'Graham Crackers'],
    inStock: true,
  },
  {
    name: 'Peanut Butter Chocolate',
    description: 'Creamy peanut butter ice cream with chocolate swirls',
    category: 'ice-cream',
    price: 6.99,
    image: '/images/products/peanut-butter.jpg',
    featured: true,
    flavors: ['Peanut Butter'],
    toppings: ['Chocolate Swirl', 'Peanut Pieces', 'Fudge Sauce'],
    inStock: true,
  },
  {
    name: 'Coconut Lime',
    description: 'Tropical coconut ice cream with zesty lime',
    category: 'ice-cream',
    price: 5.89,
    image: '/images/products/vanilla-ice-cream.jpg',
    featured: false,
    flavors: ['Coconut Lime'],
    toppings: ['Coconut Flakes', 'Lime Zest', 'Tropical Fruit'],
    inStock: true,
  },
  {
    name: 'Chocolate Orange',
    description: 'Rich chocolate ice cream with orange zest',
    category: 'ice-cream',
    price: 6.19,
    image: '/images/products/chocolate-brownie.jpg',
    featured: false,
    flavors: ['Chocolate Orange'],
    toppings: ['Orange Zest', 'Chocolate Chips', 'Candied Orange'],
    inStock: true,
  },
  {
    name: 'Maple Walnut',
    description: 'Sweet maple ice cream with crunchy walnuts',
    category: 'ice-cream',
    price: 6.49,
    image: '/images/products/vanilla-ice-cream.jpg',
    featured: false,
    flavors: ['Maple'],
    toppings: ['Walnut Pieces', 'Maple Syrup', 'Caramel Drizzle'],
    inStock: true,
  },
  {
    name: 'Cherry Garcia',
    description: 'Cherry ice cream with chocolate chunks and cherry pieces',
    category: 'ice-cream',
    price: 6.79,
    image: '/images/products/strawberry-cheesecake.jpg',
    featured: false,
    flavors: ['Cherry'],
    toppings: ['Cherry Pieces', 'Dark Chocolate Chunks', 'Cherry Sauce'],
    inStock: true,
  },
  {
    name: 'Cookies and Cream Deluxe',
    description: 'Premium cookies and cream with extra cookie pieces',
    category: 'ice-cream',
    price: 7.29,
    image: '/images/products/cookies-cream.jpg',
    featured: true,
    flavors: ['Cookies & Cream'],
    toppings: ['Extra Cookie Pieces', 'Cream Swirl', 'Chocolate Drizzle'],
    inStock: true,
  }
];

const addIceCreams = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost:27017/creamychills');
    
    await Product.insertMany(newIceCreams);
    console.log('20 new ice creams added successfully!');
    process.exit(0);
  } catch (error) {
    console.error('Error adding ice creams:', error);
    process.exit(1);
  }
};

addIceCreams();