const mongoose = require('mongoose');
const Product = require('../models/Product');
const User = require('../models/User');
require('dotenv').config();

const sampleProducts = [
  // Ice Cream (20 items)
  {
    name: 'Vanilla Bean Ice Cream',
    description: 'Classic vanilla ice cream made with real vanilla beans',
    category: 'ice-cream',
    price: 4.99,
    image: '/images/products/cookies-cream.jpg',
    featured: true,
    flavors: ['Vanilla Bean', 'French Vanilla'],
    toppings: ['Chocolate Chips', 'Sprinkles', 'Caramel Sauce', 'Hot Fudge'],
    inStock: true,
  },
  {
    name: 'Chocolate Fudge Brownie',
    description: 'Rich chocolate ice cream with fudge brownie pieces',
    category: 'ice-cream',
    price: 5.49,
    image: '/images/products/rocky-road.jpg',
    featured: true,
    flavors: ['Dark Chocolate', 'Milk Chocolate'],
    toppings: ['Brownie Pieces', 'Whipped Cream', 'Nuts'],
    inStock: true,
  },
  {
    name: 'Rainbow Sprinkle Cone',
    description: 'Colorful vanilla ice cream with rainbow sprinkles in a waffle cone',
    category: 'ice-cream',
    price: 4.49,
    image: '/images/products/rainbow-cone.jpg',
    featured: true,
    flavors: ['Vanilla', 'Strawberry', 'Chocolate'],
    toppings: ['Rainbow Sprinkles', 'Chocolate Chips', 'Gummy Bears'],
    inStock: true,
  },
  {
    name: 'Mint Chocolate Chip',
    description: 'Refreshing mint ice cream with dark chocolate chips',
    category: 'ice-cream',
    price: 5.49,
    image: '/images/products/mint-chocolate.jpg',
    featured: false,
    flavors: ['Mint', 'Peppermint'],
    toppings: ['Chocolate Chips', 'Mint Leaves', 'Chocolate Sauce'],
    inStock: true,
  },
  {
    name: 'Banana Split Sundae',
    description: 'Classic banana split with three scoops of ice cream',
    category: 'ice-cream',
    price: 8.99,
    image: '/images/products/strawberry-cheesecake.jpg',
    featured: true,
    flavors: ['Vanilla', 'Chocolate', 'Strawberry'],
    toppings: ['Banana', 'Whipped Cream', 'Cherry', 'Nuts'],
    inStock: true,
  },
  {
    name: 'Cookies & Cream',
    description: 'Vanilla ice cream loaded with chocolate cookie pieces',
    category: 'ice-cream',
    price: 5.29,
    image: '/images/products/cookies-cream.jpg',
    featured: false,
    flavors: ['Cookies & Cream'],
    toppings: ['Extra Cookies', 'Whipped Cream', 'Chocolate Sauce'],
    inStock: true,
  },
  {
    name: 'Strawberry Cheesecake',
    description: 'Creamy strawberry ice cream with cheesecake chunks',
    category: 'ice-cream',
    price: 5.99,
    image: '/images/products/pistachio.jpg',
    featured: false,
    flavors: ['Strawberry'],
    toppings: ['Graham Crackers', 'Strawberry Sauce', 'Whipped Cream'],
    inStock: true,
  },
  {
    name: 'Rocky Road',
    description: 'Chocolate ice cream with marshmallows and nuts',
    category: 'ice-cream',
    price: 5.79,
    image: '/images/products/coffee-crunch.jpg',
    featured: false,
    flavors: ['Chocolate'],
    toppings: ['Marshmallows', 'Almonds', 'Chocolate Chunks'],
    inStock: true,
  },
  {
    name: 'Pistachio Delight',
    description: 'Rich pistachio ice cream with real pistachio pieces',
    category: 'ice-cream',
    price: 6.49,
    image: '/images/products/mint-chocolate.jpg',
    featured: false,
    flavors: ['Pistachio'],
    toppings: ['Crushed Pistachios', 'Honey Drizzle'],
    inStock: true,
  },
  {
    name: 'Salted Caramel',
    description: 'Sweet and salty caramel ice cream with caramel swirls',
    category: 'ice-cream',
    price: 5.99,
    image: '/images/products/coffee-crunch.jpg',
    featured: true,
    flavors: ['Salted Caramel'],
    toppings: ['Caramel Sauce', 'Sea Salt', 'Toffee Bits'],
    inStock: true,
  },
  {
    name: 'Neapolitan Triple',
    description: 'Classic combination of vanilla, chocolate, and strawberry',
    category: 'ice-cream',
    price: 5.49,
    image: '/images/products/rainbow-cone.jpg',
    featured: false,
    flavors: ['Vanilla', 'Chocolate', 'Strawberry'],
    toppings: ['Mixed Berries', 'Chocolate Chips', 'Vanilla Wafers'],
    inStock: true,
  },
  {
    name: 'Coffee Crunch',
    description: 'Rich coffee ice cream with chocolate covered espresso beans',
    category: 'ice-cream',
    price: 5.79,
    image: '/images/products/rocky-road.jpg',
    featured: false,
    flavors: ['Coffee', 'Espresso'],
    toppings: ['Espresso Beans', 'Chocolate Sauce', 'Whipped Cream'],
    inStock: true,
  },
  {
    name: 'Mango Sorbet',
    description: 'Refreshing mango sorbet made with real mango puree',
    category: 'ice-cream',
    price: 4.99,
    image: '/images/products/lemon-meringue.jpg',
    featured: false,
    flavors: ['Mango'],
    toppings: ['Fresh Mango', 'Coconut Flakes', 'Lime Zest'],
    inStock: true,
  },
  {
    name: 'Peanut Butter Cup',
    description: 'Peanut butter ice cream with chocolate peanut butter cups',
    category: 'ice-cream',
    price: 6.29,
    image: '/images/products/peanut-butter.jpg',
    featured: true,
    flavors: ['Peanut Butter'],
    toppings: ['Peanut Butter Cups', 'Crushed Peanuts', 'Chocolate Drizzle'],
    inStock: true,
  },
  {
    name: 'Lemon Meringue',
    description: 'Tangy lemon ice cream with meringue pieces',
    category: 'ice-cream',
    price: 5.49,
    image: '/images/products/mint-chocolate.jpg',
    featured: false,
    flavors: ['Lemon'],
    toppings: ['Meringue Pieces', 'Lemon Zest', 'Graham Crackers'],
    inStock: true,
  },
  {
    name: 'Black Cherry',
    description: 'Sweet cherry ice cream with real cherry pieces',
    category: 'ice-cream',
    price: 5.29,
    image: '/images/products/rainbow-cone.jpg',
    featured: false,
    flavors: ['Cherry'],
    toppings: ['Fresh Cherries', 'Cherry Sauce', 'Chocolate Chips'],
    inStock: true,
  },
  {
    name: 'Coconut Paradise',
    description: 'Tropical coconut ice cream with toasted coconut flakes',
    category: 'ice-cream',
    price: 5.79,
    image: '/images/products/rocky-road.jpg',
    featured: false,
    flavors: ['Coconut'],
    toppings: ['Toasted Coconut', 'Pineapple', 'Macadamia Nuts'],
    inStock: true,
  },
  {
    name: 'Blueberry Cheesecake',
    description: 'Creamy cheesecake ice cream with blueberry swirls',
    category: 'ice-cream',
    price: 6.49,
    image: '/images/products/mint-chocolate.jpg',
    featured: false,
    flavors: ['Cheesecake'],
    toppings: ['Fresh Blueberries', 'Graham Crackers', 'Blueberry Sauce'],
    inStock: true,
  },
  {
    name: 'Caramel Apple Pie',
    description: 'Apple cinnamon ice cream with caramel and pie crust pieces',
    category: 'ice-cream',
    price: 6.29,
    image: '/images/products/rainbow-cone.jpg',
    featured: true,
    flavors: ['Apple Cinnamon'],
    toppings: ['Apple Pieces', 'Caramel Sauce', 'Pie Crust Crumbs'],
    inStock: true,
  },
  {
    name: 'Birthday Cake',
    description: 'Vanilla ice cream with colorful cake pieces and sprinkles',
    category: 'ice-cream',
    price: 5.99,
    image: '/images/products/rainbow-cone.jpg',
    featured: true,
    flavors: ['Vanilla Cake'],
    toppings: ['Cake Pieces', 'Rainbow Sprinkles', 'Buttercream Swirl'],
    inStock: true,
  },

  // Waffles (20 items)
  {
    name: 'Belgian Waffle',
    description: 'Crispy Belgian waffle served warm with your choice of toppings',
    category: 'waffle',
    price: 7.99,
    image: '/images/products/belgian-waffle.jpg',
    featured: true,
    customizations: [
      {
        name: 'Toppings',
        options: ['Strawberries', 'Blueberries', 'Whipped Cream', 'Maple Syrup'],
        additionalPrice: 1.50,
      },
    ],
    inStock: true,
  },
  {
    name: 'Chocolate Chip Waffle',
    description: 'Golden waffle loaded with chocolate chips and served with syrup',
    category: 'waffle',
    price: 6.99,
    image: '/images/products/strawberry-waffle.jpg',
    featured: false,
    customizations: [
      {
        name: 'Toppings',
        options: ['Ice Cream', 'Fresh Berries', 'Chocolate Sauce', 'Honey'],
        additionalPrice: 2.00,
      },
    ],
    inStock: true,
  },
  {
    name: 'Strawberry Waffle',
    description: 'Fresh waffle topped with strawberries and whipped cream',
    category: 'waffle',
    price: 8.49,
    image: '/images/products/nutella-waffle.jpg',
    featured: true,
    customizations: [
      {
        name: 'Extras',
        options: ['Extra Strawberries', 'Vanilla Ice Cream', 'Strawberry Sauce'],
        additionalPrice: 1.75,
      },
    ],
    inStock: true,
  },
  {
    name: 'Banana Nutella Waffle',
    description: 'Warm waffle with Nutella spread and fresh banana slices',
    category: 'waffle',
    price: 9.49,
    image: '/images/products/blueberry-waffle.jpg',
    featured: true,
    customizations: [
      {
        name: 'Add-ons',
        options: ['Extra Nutella', 'Chopped Hazelnuts', 'Powdered Sugar'],
        additionalPrice: 1.25,
      },
    ],
    inStock: true,
  },
  {
    name: 'Blueberry Waffle',
    description: 'Fluffy waffle with fresh blueberries and maple syrup',
    category: 'waffle',
    price: 8.29,
    image: '/images/products/caramel-apple-waffle.jpg',
    featured: false,
    customizations: [
      {
        name: 'Toppings',
        options: ['Blueberry Compote', 'Lemon Zest', 'Greek Yogurt'],
        additionalPrice: 1.50,
      },
    ],
    inStock: true,
  },
  {
    name: 'Caramel Apple Waffle',
    description: 'Cinnamon waffle with caramelized apples and caramel drizzle',
    category: 'waffle',
    price: 9.99,
    image: '/images/products/caramel-apple-waffle.jpg',
    featured: false,
    customizations: [
      {
        name: 'Extras',
        options: ['Vanilla Ice Cream', 'Cinnamon Sugar', 'Whipped Cream'],
        additionalPrice: 2.00,
      },
    ],
    inStock: true,
  },
  {
    name: 'Peanut Butter Waffle',
    description: 'Waffle with peanut butter spread and banana slices',
    category: 'waffle',
    price: 8.79,
    image: '/images/products/caramel-apple-waffle.jpg',
    featured: false,
    customizations: [
      {
        name: 'Add-ons',
        options: ['Honey Drizzle', 'Crushed Peanuts', 'Chocolate Chips'],
        additionalPrice: 1.25,
      },
    ],
    inStock: true,
  },
  {
    name: 'Red Velvet Waffle',
    description: 'Rich red velvet waffle with cream cheese frosting',
    category: 'waffle',
    price: 10.49,
    image: '/images/products/caramel-apple-waffle.jpg',
    featured: true,
    customizations: [
      {
        name: 'Toppings',
        options: ['Extra Cream Cheese', 'Fresh Berries', 'Powdered Sugar'],
        additionalPrice: 1.75,
      },
    ],
    inStock: true,
  },
  {
    name: 'Lemon Ricotta Waffle',
    description: 'Light waffle with ricotta cheese and lemon zest',
    category: 'waffle',
    price: 9.29,
    image: '/images/products/caramel-apple-waffle.jpg',
    featured: false,
    customizations: [
      {
        name: 'Toppings',
        options: ['Lemon Curd', 'Fresh Berries', 'Honey'],
        additionalPrice: 1.50,
      },
    ],
    inStock: true,
  },
  {
    name: 'Coconut Waffle',
    description: 'Tropical waffle with coconut flakes and pineapple',
    category: 'waffle',
    price: 8.99,
    image: '/images/products/caramel-apple-waffle.jpg',
    featured: false,
    customizations: [
      {
        name: 'Tropical Toppings',
        options: ['Mango Slices', 'Coconut Ice Cream', 'Passion Fruit Sauce'],
        additionalPrice: 2.25,
      },
    ],
    inStock: true,
  },
  {
    name: 'S\'mores Waffle',
    description: 'Chocolate waffle with marshmallows and graham cracker crumbs',
    category: 'waffle',
    price: 10.99,
    image: '/images/products/caramel-apple-waffle.jpg',
    featured: true,
    customizations: [
      {
        name: 'Extras',
        options: ['Extra Marshmallows', 'Chocolate Sauce', 'Vanilla Ice Cream'],
        additionalPrice: 1.75,
      },
    ],
    inStock: true,
  },
  {
    name: 'Oreo Waffle',
    description: 'Chocolate waffle with crushed Oreos and cookies & cream ice cream',
    category: 'waffle',
    price: 9.79,
    image: '/images/products/caramel-apple-waffle.jpg',
    featured: false,
    customizations: [
      {
        name: 'Add-ons',
        options: ['Extra Oreos', 'Chocolate Drizzle', 'Whipped Cream'],
        additionalPrice: 1.50,
      },
    ],
    inStock: true,
  },
  {
    name: 'Maple Pecan Waffle',
    description: 'Buttery waffle with toasted pecans and maple syrup',
    category: 'waffle',
    price: 9.49,
    image: '/images/products/caramel-apple-waffle.jpg',
    featured: false,
    customizations: [
      {
        name: 'Toppings',
        options: ['Extra Pecans', 'Butter', 'Cinnamon Sugar'],
        additionalPrice: 1.25,
      },
    ],
    inStock: true,
  },
  {
    name: 'Funfetti Waffle',
    description: 'Colorful waffle with rainbow sprinkles and vanilla glaze',
    category: 'waffle',
    price: 8.99,
    image: '/images/products/caramel-apple-waffle.jpg',
    featured: true,
    customizations: [
      {
        name: 'Fun Extras',
        options: ['Extra Sprinkles', 'Birthday Cake Ice Cream', 'Cotton Candy'],
        additionalPrice: 2.00,
      },
    ],
    inStock: true,
  },
  {
    name: 'Cinnamon Roll Waffle',
    description: 'Cinnamon-spiced waffle with cream cheese glaze',
    category: 'waffle',
    price: 9.99,
    image: '/images/products/caramel-apple-waffle.jpg',
    featured: false,
    customizations: [
      {
        name: 'Toppings',
        options: ['Extra Glaze', 'Cinnamon Sugar', 'Vanilla Ice Cream'],
        additionalPrice: 1.50,
      },
    ],
    inStock: true,
  },
  {
    name: 'Matcha Green Tea Waffle',
    description: 'Unique green tea flavored waffle with matcha powder',
    category: 'waffle',
    price: 10.29,
    image: '/images/products/caramel-apple-waffle.jpg',
    featured: false,
    customizations: [
      {
        name: 'Asian Inspired',
        options: ['Red Bean Paste', 'Mochi', 'Green Tea Ice Cream'],
        additionalPrice: 2.50,
      },
    ],
    inStock: true,
  },
  {
    name: 'Churro Waffle',
    description: 'Cinnamon sugar waffle with dulce de leche drizzle',
    category: 'waffle',
    price: 9.79,
    image: '/images/products/caramel-apple-waffle.jpg',
    featured: false,
    customizations: [
      {
        name: 'Latin Flavors',
        options: ['Extra Dulce de Leche', 'Cinnamon Sugar', 'Vanilla Ice Cream'],
        additionalPrice: 1.75,
      },
    ],
    inStock: true,
  },
  {
    name: 'Tiramisu Waffle',
    description: 'Coffee-soaked waffle with mascarpone and cocoa powder',
    category: 'waffle',
    price: 11.49,
    image: '/images/products/caramel-apple-waffle.jpg',
    featured: true,
    customizations: [
      {
        name: 'Italian Touch',
        options: ['Extra Mascarpone', 'Espresso Shot', 'Ladyfinger Cookies'],
        additionalPrice: 2.25,
      },
    ],
    inStock: true,
  },
  {
    name: 'Lavender Honey Waffle',
    description: 'Delicate lavender waffle with local honey drizzle',
    category: 'waffle',
    price: 10.99,
    image: '/images/products/caramel-apple-waffle.jpg',
    featured: false,
    customizations: [
      {
        name: 'Floral Additions',
        options: ['Extra Honey', 'Edible Flowers', 'Vanilla Bean Ice Cream'],
        additionalPrice: 2.00,
      },
    ],
    inStock: true,
  },
  {
    name: 'Salted Caramel Waffle',
    description: 'Buttery waffle with salted caramel sauce and sea salt',
    category: 'waffle',
    price: 9.99,
    image: '/images/products/caramel-apple-waffle.jpg',
    featured: true,
    customizations: [
      {
        name: 'Caramel Lovers',
        options: ['Extra Caramel', 'Sea Salt', 'Caramel Ice Cream'],
        additionalPrice: 1.75,
      },
    ],
    inStock: true,
  },

  // Cakes (20 items)
  {
    name: 'Chocolate Birthday Cake',
    description: 'Moist chocolate cake with rich chocolate frosting',
    category: 'cake',
    price: 24.99,
    image: '/images/products/black-forest.jpg',
    featured: true,
    sizes: [
      { name: 'Small (6 inch)', price: 24.99 },
      { name: 'Medium (8 inch)', price: 34.99 },
      { name: 'Large (10 inch)', price: 44.99 },
    ],
    inStock: true,
  },
  {
    name: 'Lemon Drizzle Cake',
    description: 'Moist lemon sponge cake with tangy lemon glaze',
    category: 'cake',
    price: 22.99,
    image: '/images/products/vanilla-sponge.jpg',
    featured: false,
    sizes: [
      { name: 'Small (6 inch)', price: 22.99 },
      { name: 'Medium (8 inch)', price: 32.99 },
      { name: 'Large (10 inch)', price: 42.99 },
    ],
    inStock: true,
  },
  {
    name: 'Red Velvet Cake',
    description: 'Classic red velvet cake with cream cheese frosting',
    category: 'cake',
    price: 26.99,
    image: '/images/products/carrot-cake.jpg',
    featured: true,
    sizes: [
      { name: 'Small (6 inch)', price: 26.99 },
      { name: 'Medium (8 inch)', price: 36.99 },
      { name: 'Large (10 inch)', price: 46.99 },
    ],
    inStock: true,
  },
  {
    name: 'Vanilla Sponge Cake',
    description: 'Light and fluffy vanilla sponge with buttercream frosting',
    category: 'cake',
    price: 21.99,
    image: '/images/products/strawberry-shortcake.jpg',
    featured: false,
    sizes: [
      { name: 'Small (6 inch)', price: 21.99 },
      { name: 'Medium (8 inch)', price: 31.99 },
      { name: 'Large (10 inch)', price: 41.99 },
    ],
    inStock: true,
  },
  {
    name: 'Carrot Cake',
    description: 'Spiced carrot cake with cream cheese frosting and walnuts',
    category: 'cake',
    price: 25.99,
    image: '/images/products/black-forest.jpg',
    featured: false,
    sizes: [
      { name: 'Small (6 inch)', price: 25.99 },
      { name: 'Medium (8 inch)', price: 35.99 },
      { name: 'Large (10 inch)', price: 45.99 },
    ],
    inStock: true,
  },
  {
    name: 'Black Forest Cake',
    description: 'Chocolate cake with cherries and whipped cream',
    category: 'cake',
    price: 28.99,
    image: '/images/products/carrot-cake.jpg',
    featured: true,
    sizes: [
      { name: 'Small (6 inch)', price: 28.99 },
      { name: 'Medium (8 inch)', price: 38.99 },
      { name: 'Large (10 inch)', price: 48.99 },
    ],
    inStock: true,
  },
  {
    name: 'Strawberry Shortcake',
    description: 'Vanilla sponge with fresh strawberries and whipped cream',
    category: 'cake',
    price: 24.99,
    image: '/images/products/lemon-cake.jpg',
    featured: false,
    sizes: [
      { name: 'Small (6 inch)', price: 24.99 },
      { name: 'Medium (8 inch)', price: 34.99 },
      { name: 'Large (10 inch)', price: 44.99 },
    ],
    inStock: true,
  },
  {
    name: 'Tiramisu Cake',
    description: 'Coffee-soaked sponge with mascarpone and cocoa',
    category: 'cake',
    price: 29.99,
    image: '/images/products/carrot-cake.jpg',
    featured: true,
    sizes: [
      { name: 'Small (6 inch)', price: 29.99 },
      { name: 'Medium (8 inch)', price: 39.99 },
      { name: 'Large (10 inch)', price: 49.99 },
    ],
    inStock: true,
  },
  {
    name: 'Funfetti Cake',
    description: 'Colorful vanilla cake with rainbow sprinkles',
    category: 'cake',
    price: 23.99,
    image: '/images/products/lemon-cake.jpg',
    featured: true,
    sizes: [
      { name: 'Small (6 inch)', price: 23.99 },
      { name: 'Medium (8 inch)', price: 33.99 },
      { name: 'Large (10 inch)', price: 43.99 },
    ],
    inStock: true,
  },
  {
    name: 'Cheesecake',
    description: 'Rich and creamy New York style cheesecake',
    category: 'cake',
    price: 27.99,
    image: '/images/products/lemon-cake.jpg',
    featured: false,
    sizes: [
      { name: 'Small (6 inch)', price: 27.99 },
      { name: 'Medium (8 inch)', price: 37.99 },
      { name: 'Large (10 inch)', price: 47.99 },
    ],
    inStock: true,
  },
  {
    name: 'German Chocolate Cake',
    description: 'Rich chocolate cake with coconut pecan frosting',
    category: 'cake',
    price: 26.99,
    image: '/images/products/black-forest.jpg',
    featured: false,
    sizes: [
      { name: 'Small (6 inch)', price: 26.99 },
      { name: 'Medium (8 inch)', price: 36.99 },
      { name: 'Large (10 inch)', price: 46.99 },
    ],
    inStock: true,
  },
  {
    name: 'Lemon Blueberry Cake',
    description: 'Lemon cake with fresh blueberries and lemon buttercream',
    category: 'cake',
    price: 25.99,
    image: '/images/products/lemon-cake.jpg',
    featured: false,
    sizes: [
      { name: 'Small (6 inch)', price: 25.99 },
      { name: 'Medium (8 inch)', price: 35.99 },
      { name: 'Large (10 inch)', price: 45.99 },
    ],
    inStock: true,
  },
  {
    name: 'Coconut Cake',
    description: 'Tropical coconut cake with coconut cream frosting',
    category: 'cake',
    price: 24.99,
    image: '/images/products/lemon-cake.jpg',
    featured: false,
    sizes: [
      { name: 'Small (6 inch)', price: 24.99 },
      { name: 'Medium (8 inch)', price: 34.99 },
      { name: 'Large (10 inch)', price: 44.99 },
    ],
    inStock: true,
  },
  {
    name: 'Pineapple Upside Down Cake',
    description: 'Classic upside down cake with caramelized pineapple',
    category: 'cake',
    price: 23.99,
    image: '/images/products/vanilla-sponge.jpg',
    featured: false,
    sizes: [
      { name: 'Small (6 inch)', price: 23.99 },
      { name: 'Medium (8 inch)', price: 33.99 },
      { name: 'Large (10 inch)', price: 43.99 },
    ],
    inStock: true,
  },
  {
    name: 'Banoffee Cake',
    description: 'Banana cake with toffee and whipped cream',
    category: 'cake',
    price: 26.99,
    image: '/images/products/carrot-cake.jpg',
    featured: false,
    sizes: [
      { name: 'Small (6 inch)', price: 26.99 },
      { name: 'Medium (8 inch)', price: 36.99 },
      { name: 'Large (10 inch)', price: 46.99 },
    ],
    inStock: true,
  },
  {
    name: 'Salted Caramel Cake',
    description: 'Vanilla cake with salted caramel buttercream',
    category: 'cake',
    price: 27.99,
    image: '/images/products/carrot-cake.jpg',
    featured: true,
    sizes: [
      { name: 'Small (6 inch)', price: 27.99 },
      { name: 'Medium (8 inch)', price: 37.99 },
      { name: 'Large (10 inch)', price: 47.99 },
    ],
    inStock: true,
  },
  {
    name: 'Oreo Cake',
    description: 'Chocolate cake with Oreo cookies and cream frosting',
    category: 'cake',
    price: 25.99,
    image: '/images/products/carrot-cake.jpg',
    featured: true,
    sizes: [
      { name: 'Small (6 inch)', price: 25.99 },
      { name: 'Medium (8 inch)', price: 35.99 },
      { name: 'Large (10 inch)', price: 45.99 },
    ],
    inStock: true,
  },
  {
    name: 'Matcha Green Tea Cake',
    description: 'Delicate green tea sponge with matcha buttercream',
    category: 'cake',
    price: 28.99,
    image: '/images/products/strawberry-shortcake.jpg',
    featured: false,
    sizes: [
      { name: 'Small (6 inch)', price: 28.99 },
      { name: 'Medium (8 inch)', price: 38.99 },
      { name: 'Large (10 inch)', price: 48.99 },
    ],
    inStock: true,
  },
  {
    name: 'Tres Leches Cake',
    description: 'Sponge cake soaked in three types of milk',
    category: 'cake',
    price: 26.99,
    image: '/images/products/lemon-cake.jpg',
    featured: false,
    sizes: [
      { name: 'Small (6 inch)', price: 26.99 },
      { name: 'Medium (8 inch)', price: 36.99 },
      { name: 'Large (10 inch)', price: 46.99 },
    ],
    inStock: true,
  },
  {
    name: 'Opera Cake',
    description: 'French layered cake with chocolate and coffee',
    category: 'cake',
    price: 32.99,
    image: '/images/products/red-velvet-cake.jpg',
    featured: true,
    sizes: [
      { name: 'Small (6 inch)', price: 32.99 },
      { name: 'Medium (8 inch)', price: 42.99 },
      { name: 'Large (10 inch)', price: 52.99 },
    ],
    inStock: true,
  },

  // Milkshakes (20 items)
  {
    name: 'Strawberry Milkshake',
    description: 'Creamy strawberry milkshake made with fresh strawberries',
    category: 'milkshake',
    price: 5.99,
    image: '/images/products/strawberry-milkshake.jpg',
    featured: false,
    flavors: ['Strawberry', 'Vanilla Strawberry'],
    customizations: [
      {
        name: 'Size',
        options: ['Regular', 'Large'],
        additionalPrice: 1.00,
      },
    ],
    inStock: true,
  },
  {
    name: 'Unicorn Milkshake',
    description: 'Magical pink and blue milkshake topped with whipped cream and sprinkles',
    category: 'milkshake',
    price: 7.99,
    image: '/images/products/unicorn-milkshake.jpg',
    featured: true,
    flavors: ['Cotton Candy', 'Bubblegum'],
    customizations: [
      {
        name: 'Toppings',
        options: ['Whipped Cream', 'Rainbow Sprinkles', 'Marshmallows', 'Edible Glitter'],
        additionalPrice: 1.50,
      },
    ],
    inStock: true,
  },
  {
    name: 'Oreo Milkshake',
    description: 'Thick and creamy milkshake blended with Oreo cookies',
    category: 'milkshake',
    price: 6.49,
    image: '/images/products/strawberry-milkshake.jpg',
    featured: false,
    flavors: ['Cookies & Cream'],
    customizations: [
      {
        name: 'Extra Toppings',
        options: ['Extra Oreos', 'Whipped Cream', 'Chocolate Drizzle'],
        additionalPrice: 1.00,
      },
    ],
    inStock: true,
  },
  {
    name: 'Chocolate Peanut Butter Milkshake',
    description: 'Rich chocolate and peanut butter milkshake',
    category: 'milkshake',
    price: 6.99,
    image: '/images/products/unicorn-milkshake.jpg',
    featured: true,
    flavors: ['Chocolate Peanut Butter'],
    customizations: [
      {
        name: 'Add-ons',
        options: ['Peanut Butter Cups', 'Whipped Cream', 'Chocolate Sauce'],
        additionalPrice: 1.25,
      },
    ],
    inStock: true,
  },
  {
    name: 'Vanilla Bean Milkshake',
    description: 'Classic vanilla milkshake made with real vanilla beans',
    category: 'milkshake',
    price: 5.49,
    image: '/images/products/vanilla-shake.jpg',
    featured: false,
    flavors: ['Vanilla Bean'],
    customizations: [
      {
        name: 'Toppings',
        options: ['Whipped Cream', 'Caramel Sauce', 'Vanilla Wafers'],
        additionalPrice: 0.75,
      },
    ],
    inStock: true,
  },
  {
    name: 'Salted Caramel Milkshake',
    description: 'Sweet and salty caramel milkshake with sea salt',
    category: 'milkshake',
    price: 6.79,
    image: '/images/products/chocolate-pb-shake.jpg',
    featured: false,
    flavors: ['Salted Caramel'],
    customizations: [
      {
        name: 'Extras',
        options: ['Extra Caramel', 'Sea Salt', 'Toffee Bits'],
        additionalPrice: 1.00,
      },
    ],
    inStock: true,
  },
  {
    name: 'Mint Chocolate Chip Milkshake',
    description: 'Refreshing mint milkshake with chocolate chips',
    category: 'milkshake',
    price: 6.29,
    image: '/images/products/coffee-shake.jpg',
    featured: false,
    flavors: ['Mint Chocolate Chip'],
    customizations: [
      {
        name: 'Add-ons',
        options: ['Extra Chocolate Chips', 'Mint Leaves', 'Whipped Cream'],
        additionalPrice: 0.75,
      },
    ],
    inStock: true,
  },
  {
    name: 'Birthday Cake Milkshake',
    description: 'Vanilla milkshake with birthday cake pieces and sprinkles',
    category: 'milkshake',
    price: 7.49,
    image: '/images/products/unicorn-milkshake.jpg',
    featured: true,
    flavors: ['Birthday Cake'],
    customizations: [
      {
        name: 'Party Extras',
        options: ['Extra Cake Pieces', 'Rainbow Sprinkles', 'Buttercream Swirl'],
        additionalPrice: 1.25,
      },
    ],
    inStock: true,
  },
  {
    name: 'Banana Split Milkshake',
    description: 'Banana milkshake with strawberry and chocolate swirls',
    category: 'milkshake',
    price: 6.99,
    image: '/images/products/banana-split-shake.jpg',
    featured: false,
    flavors: ['Banana'],
    customizations: [
      {
        name: 'Sundae Toppings',
        options: ['Cherry', 'Nuts', 'Whipped Cream', 'Chocolate Sauce'],
        additionalPrice: 1.50,
      },
    ],
    inStock: true,
  },
  {
    name: 'Coffee Milkshake',
    description: 'Rich coffee milkshake with espresso and vanilla ice cream',
    category: 'milkshake',
    price: 6.49,
    image: '/images/products/unicorn-milkshake.jpg',
    featured: false,
    flavors: ['Coffee', 'Espresso'],
    customizations: [
      {
        name: 'Coffee Extras',
        options: ['Extra Shot', 'Whipped Cream', 'Cinnamon'],
        additionalPrice: 1.00,
      },
    ],
    inStock: true,
  },
  {
    name: 'Rocky Road Milkshake',
    description: 'Chocolate milkshake with marshmallows and nuts',
    category: 'milkshake',
    price: 7.29,
    image: '/images/products/coffee-shake.jpg',
    featured: false,
    flavors: ['Chocolate'],
    customizations: [
      {
        name: 'Rocky Extras',
        options: ['Extra Marshmallows', 'Almonds', 'Chocolate Chunks'],
        additionalPrice: 1.25,
      },
    ],
    inStock: true,
  },
  {
    name: 'Cookies & Cream Milkshake',
    description: 'Vanilla milkshake blended with chocolate sandwich cookies',
    category: 'milkshake',
    price: 6.79,
    image: '/images/products/chocolate-pb-shake.jpg',
    featured: false,
    flavors: ['Cookies & Cream'],
    customizations: [
      {
        name: 'Cookie Extras',
        options: ['Extra Cookies', 'Cookie Crumbs', 'Vanilla Wafers'],
        additionalPrice: 1.00,
      },
    ],
    inStock: true,
  },
  {
    name: 'Strawberry Cheesecake Milkshake',
    description: 'Creamy cheesecake milkshake with strawberry swirls',
    category: 'milkshake',
    price: 7.99,
    image: '/images/products/strawberry-milkshake.jpg',
    featured: true,
    flavors: ['Strawberry Cheesecake'],
    customizations: [
      {
        name: 'Cheesecake Extras',
        options: ['Graham Crackers', 'Fresh Strawberries', 'Cream Cheese Swirl'],
        additionalPrice: 1.50,
      },
    ],
    inStock: true,
  },
  {
    name: 'Nutella Milkshake',
    description: 'Rich hazelnut chocolate milkshake with Nutella',
    category: 'milkshake',
    price: 7.49,
    image: '/images/products/chocolate-pb-shake.jpg',
    featured: false,
    flavors: ['Nutella'],
    customizations: [
      {
        name: 'Nutella Extras',
        options: ['Extra Nutella', 'Hazelnuts', 'Chocolate Drizzle'],
        additionalPrice: 1.25,
      },
    ],
    inStock: true,
  },
  {
    name: 'Coconut Milkshake',
    description: 'Tropical coconut milkshake with coconut flakes',
    category: 'milkshake',
    price: 6.29,
    image: '/images/products/coffee-shake.jpg',
    featured: false,
    flavors: ['Coconut'],
    customizations: [
      {
        name: 'Tropical Extras',
        options: ['Toasted Coconut', 'Pineapple', 'Mango'],
        additionalPrice: 1.00,
      },
    ],
    inStock: true,
  },
  {
    name: 'Malted Chocolate Milkshake',
    description: 'Classic malted chocolate milkshake with malt powder',
    category: 'milkshake',
    price: 6.99,
    image: '/images/products/birthday-shake.jpg',
    featured: false,
    flavors: ['Malted Chocolate'],
    customizations: [
      {
        name: 'Malt Extras',
        options: ['Extra Malt', 'Whipped Cream', 'Chocolate Sauce'],
        additionalPrice: 1.00,
      },
    ],
    inStock: true,
  },
  {
    name: 'Blueberry Pie Milkshake',
    description: 'Blueberry milkshake with pie crust pieces',
    category: 'milkshake',
    price: 7.79,
    image: '/images/products/strawberry-milkshake.jpg',
    featured: false,
    flavors: ['Blueberry'],
    customizations: [
      {
        name: 'Pie Extras',
        options: ['Fresh Blueberries', 'Pie Crust Crumbs', 'Cinnamon'],
        additionalPrice: 1.25,
      },
    ],
    inStock: true,
  },
  {
    name: 'Caramel Apple Milkshake',
    description: 'Apple cinnamon milkshake with caramel drizzle',
    category: 'milkshake',
    price: 7.29,
    image: '/images/products/chocolate-pb-shake.jpg',
    featured: false,
    flavors: ['Apple Cinnamon'],
    customizations: [
      {
        name: 'Apple Extras',
        options: ['Caramel Sauce', 'Apple Pieces', 'Cinnamon Sugar'],
        additionalPrice: 1.00,
      },
    ],
    inStock: true,
  },
  {
    name: 'S\'mores Milkshake',
    description: 'Chocolate milkshake with marshmallows and graham crackers',
    category: 'milkshake',
    price: 8.49,
    image: '/images/products/banana-split-shake.jpg',
    featured: true,
    flavors: ['Chocolate'],
    customizations: [
      {
        name: 'Campfire Extras',
        options: ['Toasted Marshmallows', 'Graham Crackers', 'Chocolate Chunks'],
        additionalPrice: 1.50,
      },
    ],
    inStock: true,
  },
  {
    name: 'Pistachio Milkshake',
    description: 'Unique pistachio milkshake with real pistachio pieces',
    category: 'milkshake',
    price: 7.99,
    image: '/images/products/chocolate-pb-shake.jpg',
    featured: false,
    flavors: ['Pistachio'],
    customizations: [
      {
        name: 'Nut Extras',
        options: ['Crushed Pistachios', 'Honey', 'Rose Water'],
        additionalPrice: 1.25,
      },
    ],
    inStock: true,
  },

  // Drinks (20 items)
  {
    name: 'Iced Coffee',
    description: 'Cold brew coffee served over ice',
    category: 'drink',
    price: 3.99,
    image: '/images/products/iced-coffee.jpg',
    featured: false,
    customizations: [
      {
        name: 'Milk',
        options: ['Regular', 'Almond', 'Oat', 'Coconut'],
        additionalPrice: 0.50,
      },
    ],
    inStock: true,
  },
  {
    name: 'Hot Chocolate',
    description: 'Rich and creamy hot chocolate topped with marshmallows',
    category: 'drink',
    price: 4.49,
    image: '/images/products/hot-chocolate.jpg',
    featured: false,
    customizations: [
      {
        name: 'Extras',
        options: ['Marshmallows', 'Whipped Cream', 'Cinnamon', 'Caramel Syrup'],
        additionalPrice: 0.75,
      },
    ],
    inStock: true,
  },
  {
    name: 'Iced Tea',
    description: 'Refreshing iced tea with lemon',
    category: 'drink',
    price: 2.99,
    image: '/images/products/lemonade.jpg',
    featured: false,
    customizations: [
      {
        name: 'Flavors',
        options: ['Lemon', 'Peach', 'Raspberry', 'Green Tea'],
        additionalPrice: 0.25,
      },
    ],
    inStock: true,
  },
  {
    name: 'Lemonade',
    description: 'Fresh squeezed lemonade',
    category: 'drink',
    price: 3.49,
    image: '/images/products/iced-coffee.jpg',
    featured: false,
    customizations: [
      {
        name: 'Flavors',
        options: ['Strawberry', 'Pink', 'Mango', 'Mint'],
        additionalPrice: 0.50,
      },
    ],
    inStock: true,
  },
  {
    name: 'Cappuccino',
    description: 'Espresso with steamed milk and foam',
    category: 'drink',
    price: 4.29,
    image: '/images/products/hot-chocolate.jpg',
    featured: false,
    customizations: [
      {
        name: 'Syrups',
        options: ['Vanilla', 'Caramel', 'Hazelnut', 'Cinnamon'],
        additionalPrice: 0.50,
      },
    ],
    inStock: true,
  },
  {
    name: 'Matcha Latte',
    description: 'Green tea matcha with steamed milk',
    category: 'drink',
    price: 4.99,
    image: '/images/products/matcha-latte.jpg',
    featured: true,
    customizations: [
      {
        name: 'Milk Options',
        options: ['Almond', 'Coconut', 'Oat', 'Soy'],
        additionalPrice: 0.50,
      },
    ],
    inStock: true,
  },
  {
    name: 'Chai Latte',
    description: 'Spiced chai tea with steamed milk',
    category: 'drink',
    price: 4.49,
    image: '/images/products/matcha-latte.jpg',
    featured: false,
    customizations: [
      {
        name: 'Spices',
        options: ['Extra Cinnamon', 'Cardamom', 'Ginger', 'Vanilla'],
        additionalPrice: 0.25,
      },
    ],
    inStock: true,
  },
  {
    name: 'Smoothie Bowl Drink',
    description: 'Blended fruit smoothie in a cup',
    category: 'drink',
    price: 5.99,
    image: '/images/products/lemonade.jpg',
    featured: true,
    customizations: [
      {
        name: 'Fruits',
        options: ['Mango', 'Berry Mix', 'Tropical', 'Green'],
        additionalPrice: 1.00,
      },
    ],
    inStock: true,
  },
  {
    name: 'Italian Soda',
    description: 'Sparkling water with flavored syrup',
    category: 'drink',
    price: 3.29,
    image: '/images/products/iced-coffee.jpg',
    featured: false,
    customizations: [
      {
        name: 'Flavors',
        options: ['Cherry', 'Vanilla', 'Raspberry', 'Orange'],
        additionalPrice: 0.25,
      },
    ],
    inStock: true,
  },
  {
    name: 'Frappé',
    description: 'Iced coffee drink blended with ice',
    category: 'drink',
    price: 4.79,
    image: '/images/products/iced-coffee.jpg',
    featured: false,
    customizations: [
      {
        name: 'Flavors',
        options: ['Caramel', 'Mocha', 'Vanilla', 'Hazelnut'],
        additionalPrice: 0.50,
      },
    ],
    inStock: true,
  },
  {
    name: 'Bubble Tea',
    description: 'Tea with chewy tapioca pearls',
    category: 'drink',
    price: 5.49,
    image: '/images/products/hot-chocolate.jpg',
    featured: true,
    customizations: [
      {
        name: 'Tea Base',
        options: ['Black Tea', 'Green Tea', 'Taro', 'Thai Tea'],
        additionalPrice: 0.50,
      },
    ],
    inStock: true,
  },
  {
    name: 'Arnold Palmer',
    description: 'Half iced tea, half lemonade',
    category: 'drink',
    price: 3.79,
    image: '/images/products/iced-coffee.jpg',
    featured: false,
    customizations: [
      {
        name: 'Variations',
        options: ['Sweet Tea', 'Green Tea', 'Flavored Lemonade'],
        additionalPrice: 0.25,
      },
    ],
    inStock: true,
  },
  {
    name: 'Affogato',
    description: 'Vanilla ice cream drowned in hot espresso',
    category: 'drink',
    price: 5.99,
    image: '/images/products/cappuccino.jpg',
    featured: true,
    customizations: [
      {
        name: 'Ice Cream',
        options: ['Vanilla', 'Chocolate', 'Caramel', 'Hazelnut'],
        additionalPrice: 1.00,
      },
    ],
    inStock: true,
  },
  {
    name: 'Golden Milk Latte',
    description: 'Turmeric latte with warming spices',
    category: 'drink',
    price: 4.99,
    image: '/images/products/hot-chocolate.jpg',
    featured: false,
    customizations: [
      {
        name: 'Milk',
        options: ['Coconut', 'Almond', 'Oat', 'Regular'],
        additionalPrice: 0.50,
      },
    ],
    inStock: true,
  },
  {
    name: 'Horchata',
    description: 'Traditional rice and cinnamon drink',
    category: 'drink',
    price: 4.29,
    image: '/images/products/lemonade.jpg',
    featured: false,
    customizations: [
      {
        name: 'Spices',
        options: ['Extra Cinnamon', 'Vanilla', 'Condensed Milk'],
        additionalPrice: 0.50,
      },
    ],
    inStock: true,
  },
  {
    name: 'Lavender Honey Latte',
    description: 'Floral latte with lavender and honey',
    category: 'drink',
    price: 5.29,
    image: '/images/products/cappuccino.jpg',
    featured: false,
    customizations: [
      {
        name: 'Extras',
        options: ['Extra Honey', 'Oat Milk', 'Dried Lavender'],
        additionalPrice: 0.50,
      },
    ],
    inStock: true,
  },
  {
    name: 'Cold Brew Float',
    description: 'Cold brew coffee with vanilla ice cream float',
    category: 'drink',
    price: 5.79,
    image: '/images/products/iced-tea.jpg',
    featured: true,
    customizations: [
      {
        name: 'Ice Cream',
        options: ['Vanilla', 'Coffee', 'Caramel', 'Chocolate'],
        additionalPrice: 1.00,
      },
    ],
    inStock: true,
  },
  {
    name: 'Hibiscus Tea',
    description: 'Floral herbal tea served hot or iced',
    category: 'drink',
    price: 3.99,
    image: '/images/products/cappuccino.jpg',
    featured: false,
    customizations: [
      {
        name: 'Additions',
        options: ['Honey', 'Lemon', 'Mint', 'Ginger'],
        additionalPrice: 0.25,
      },
    ],
    inStock: true,
  },
  {
    name: 'Nitro Cold Brew',
    description: 'Cold brew coffee infused with nitrogen',
    category: 'drink',
    price: 4.99,
    image: '/images/products/iced-coffee.jpg',
    featured: false,
    customizations: [
      {
        name: 'Flavors',
        options: ['Vanilla', 'Caramel', 'Chocolate', 'Plain'],
        additionalPrice: 0.50,
      },
    ],
    inStock: true,
  },
  {
    name: 'Seasonal Spiced Cider',
    description: 'Warm apple cider with seasonal spices',
    category: 'drink',
    price: 4.49,
    image: '/images/products/cappuccino.jpg',
    featured: true,
    customizations: [
      {
        name: 'Spices',
        options: ['Cinnamon Stick', 'Star Anise', 'Orange Peel', 'Cloves'],
        additionalPrice: 0.25,
      },
    ],
    inStock: true,
  },
];

const sampleAdmin = {
  name: 'Admin User',
  email: 'admin@creamychills.com',
  password: 'admin123',
  role: 'admin',
};

const seedDatabase = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost:27017/creamychills');
    
    // Clear existing data
    await Product.deleteMany({});
    await User.deleteMany({});
    
    // Insert sample products
    await Product.insertMany(sampleProducts);
    console.log('Sample products inserted');
    
    // Insert admin user
    const admin = new User(sampleAdmin);
    await admin.save();
    console.log('Admin user created');
    
    console.log('Database seeded successfully!');
    process.exit(0);
  } catch (error) {
    console.error('Error seeding database:', error);
    process.exit(1);
  }
};

seedDatabase();